<?php
// set site name
$config['site_name'] = 'Vendhouse';
$config['my_database'] = 'wwwvendhousecom_db';
$config['total_sms'] = 35;

// all month
$config['months'] = array(
    'January', 'February', 'March', 'April',
    'May', 'June', 'July', 'August',
    'September', 'October', 'November', 'December'
);

// print heading
$config['heading'] = array(
    'title' => 'VendhouseBD.com',
    'place' => 'Mymensingh, Sadar',
    'mobile'=> '01XXX-XXXXXX'
);

// Designation
$config['desigation'] = array(
    'পরিচালক',
    'অফিস সহকারী',
    'হিসাবরক্ষক',
    'নিরাপত্তা রক্ষী',
    'সেলসম্যান',
    'ম্যানেজার'
);

//unit
$config['unit'] = array(
    "PCS",
    "Set",
    "Pair",
    "Kg",
    "Gm",
    "Miter",
    "MM",
    "Liter",
    "Packet",
    "Yard",
    "Feet",
    "Foot",
    "Pound"
);

// Color
$config['color'] = array(
    "White",
    "Red",
    "Black",
    "Purple",
    "Green",
    "Orange"
);

// Size
$config['size'] = array(
    "Small",
    "Medium",
    "Large",
    "Extra Large"
);


// All Upazila
$config['upazila'] = [
	'1' => 'Amtali',
	'2' => 'Bamna',
	'3' => 'Barguna-S',
	'4' => 'Betagi',
	'5' => 'Patharghata',
	'6' => 'Taltali',
	'7' => 'Agailjhara',
	'8' => 'Babuganj',
	'9' => 'Bakerganj',
	'10' => 'Banaripara',
	'11' => 'Barishal-S',
	'12' => 'Gouranadi',
	'13' => 'Hizla',
	'14' => 'Mehendiganj',
	'15' => 'Muladi',
	'16' => 'Uzirpur',
	'17' => 'Bhola-S',
	'18' => 'Borhanuddin',
	'19' => 'Charfassion',
	'20' => 'Daulatkhan',
	'21' => 'Lalmohan',
	'22' => 'Monpura',
	'23' => 'Tazumuddin',
	'24' => 'Jhalokathi-S',
	'25' => 'Kathalia',
	'26' => 'Nalchity',
	'27' => 'Rajapur',
	'28' => 'Bauphal',
	'29' => 'Dashmina',
	'30' => 'Dumki',
	'31' => 'Galachipa',
	'32' => 'Kalapara',
	'33' => 'Mirjaganj',
	'34' => 'Patuakhali-S',
	'35' => 'Rangabali',
	'36' => 'Bhandaria',
	'37' => 'Kawkhali',
	'38' => 'Mothbaria',
	'39' => 'Nazirpur',
	'40' => 'Nesarabad',
	'41' => 'Pirojpur-S',
	'42' => 'Zianagar',
	'43' => 'Akhaura',
	'44' => 'Ashuganj',
	'45' => 'B.Baria-S',
	'46' => 'Bancharampur',
	'47' => 'Bijoynagar',
	'48' => 'Kasba',
	'49' => 'Nabinagar',
	'50' => 'Nasirnagar',
	'51' => 'Sarail',
	'52' => 'Alikadam',
	'53' => 'Bandarban-S',
	'54' => 'Lama',
	'55' => 'Naikhyongchari',
	'56' => 'Rowangchari',
	'57' => 'Ruma',
	'58' => 'Thanchi',
	'59' => 'Chandpur-S',
	'60' => 'Faridganj',
	'61' => 'Haimchar',
	'62' => 'Haziganj',
	'63' => 'Kachua',
	'64' => 'Matlab (Dakshin)',
	'65' => 'Matlab (Uttar)',
	'66' => 'Shahrasti',
	'67' => 'Anwara',
	'68' => 'Banskhali',
	'69' => 'Boalkhali',
	'70' => 'Chandanish',
	'71' => 'Fatikchari',
	'72' => 'Hathazari',
	'73' => 'Karnaphuli',
	'74' => 'Lohagara',
	'75' => 'Mirsharai',
	'76' => 'Patiya',
	'77' => 'Rangunia',
	'78' => 'Raojan',
	'79' => 'Sandwip',
	'80' => 'Satkania',
	'81' => 'Sitakunda',
	'82' => 'Chakoria',
	'83' => 'Cox\'S Bazar-S',
	'84' => 'Kutubdia',
	'85' => 'Moheskhali',
	'86' => 'Pekua',
	'87' => 'Ramu',
	'88' => 'Teknaf',
	'89' => 'Ukhiya',
	'90' => 'Barura',
	'91' => 'Brahmanpara',
	'92' => 'Burichong',
	'93' => 'Chandina',
	'94' => 'Chouddagram',
	'95' => 'Cumilla-S',
	'96' => 'Cumilla-S Daksin',
	'97' => 'Daudkandi',
	'98' => 'Debidwar',
	'99' => 'Homna',
	'100' => 'Laksham',
	'101' => 'Lalmai',
	'102' => 'Meghna',
	'103' => 'Monohorganj',
	'104' => 'Muradnagar',
	'105' => 'Nangalkot',
	'106' => 'Titas',
	'107' => 'Chhagalniya',
	'108' => 'Daganbhuiyan',
	'109' => 'Feni-S',
	'110' => 'Fulgazi',
	'111' => 'Porshuram',
	'112' => 'Sonagazi',
	'113' => 'Dighinala',
	'114' => 'Guimara',
	'115' => 'Khagrachari-S',
	'116' => 'Laxmichari',
	'117' => 'Mahalchari',
	'118' => 'Manikchari',
	'119' => 'Matiranga',
	'120' => 'Panchari',
	'121' => 'Ramgarh',
	'122' => 'Komol Nagar',
	'123' => 'Laxmipur-S',
	'124' => 'Raipur',
	'125' => 'Ramganj',
	'126' => 'Ramgati',
	'127' => 'Begumganj',
	'128' => 'Chatkhil',
	'129' => 'Companiganj',
	'130' => 'Hatiya',
	'131' => 'Kabir Hat',
	'132' => 'Noakhali-S',
	'133' => 'Senbag',
	'134' => 'Sonaimuri',
	'135' => 'Subarna Char',
	'136' => 'Baghaichari',
	'137' => 'Barkal',
	'138' => 'Belaichari',
	'139' => 'Juraichari',
	'140' => 'Kaptai',
	'141' => 'Kaukhali',
	'142' => 'Langadu',
	'143' => 'Nanniarchar',
	'144' => 'Rajosthali',
	'145' => 'Rangamati-S',
	'146' => 'Dhamrai',
	'147' => 'Dohar',
	'148' => 'Keraniganj',
	'149' => 'Nawabganj',
	'150' => 'Savar',
	'151' => 'Alfadanga',
	'152' => 'Bhanga',
	'153' => 'Boalmari',
	'154' => 'Charbhadrasan',
	'155' => 'Faridpur-S',
	'156' => 'Madhukhali',
	'157' => 'Nagarkanda',
	'158' => 'Sadarpur',
	'159' => 'Saltha',
	'160' => 'Gazipur-S',
	'161' => 'Kaliakoir',
	'162' => 'Kaliganj',
	'163' => 'Kapasia',
	'164' => 'Sreepur',
	'165' => 'Gopalganj-S',
	'166' => 'Kasiani',
	'167' => 'Kotwalipara',
	'168' => 'Muksudpur',
	'169' => 'Tungipara',
	'170' => 'Austagram',
	'171' => 'Bajitpur',
	'172' => 'Bhairab',
	'173' => 'Hossainpur',
	'174' => 'Itna',
	'175' => 'Karimganj',
	'176' => 'Katiadi',
	'177' => 'Kishoreganj-S',
	'178' => 'Kuliarchar',
	'179' => 'Mithamoin',
	'180' => 'Nikli',
	'181' => 'Pakundia',
	'182' => 'Tarail',
	'183' => 'Kalkini',
	'184' => 'Madaripur-S',
	'185' => 'Rajoir',
	'186' => 'Shibchar',
	'187' => 'Daulatpur',
	'188' => 'Ghior',
	'189' => 'Harirampur',
	'190' => 'Manikganj-S',
	'191' => 'Saturia',
	'192' => 'Shivalaya',
	'193' => 'Singair',
	'194' => 'Gazaria',
	'195' => 'Lauhajong',
	'196' => 'Munshiganj-S',
	'197' => 'Sirajdikhan',
	'198' => 'Sreenagar',
	'199' => 'Tongibari',
	'200' => 'Araihazar',
	'201' => 'Bandar',
	'202' => 'Narayanganj-S',
	'203' => 'Rupganj',
	'204' => 'Sonargaon',
	'205' => 'Belabo',
	'206' => 'Monohardi',
	'207' => 'Narshingdi-S',
	'208' => 'Palash',
	'209' => 'Raipura',
	'210' => 'Shibpur',
	'211' => 'Baliakandi',
	'212' => 'Goalanda',
	'213' => 'Kalukhali',
	'214' => 'Pangsha',
	'215' => 'Rajbari-S',
	'216' => 'Bhedarganj',
	'217' => 'Damuddya',
	'218' => 'Goshairhat',
	'219' => 'Janjira',
	'220' => 'Naria',
	'221' => 'Shariatpur-S',
	'222' => 'Basail',
	'223' => 'Bhuapur',
	'224' => 'Delduar',
	'225' => 'Dhanbari',
	'226' => 'Ghatail',
	'227' => 'Gopalpur',
	'228' => 'Kalihati',
	'229' => 'Madhupur',
	'230' => 'Mirzapur',
	'231' => 'Nagarpur',
	'232' => 'Shakhipur',
	'233' => 'Tangail-S',
	'234' => 'Bagerhat-S',
	'235' => 'Chitalmari',
	'236' => 'Fakirhat',
	'237' => 'Kachua',
	'238' => 'Mollahat',
	'239' => 'Mongla',
	'240' => 'Morrelganj',
	'241' => 'Rampal',
	'242' => 'Sharankhola',
	'243' => 'Alamdanga',
	'244' => 'Chuadanga-S',
	'245' => 'Damurhuda',
	'246' => 'Jibannagar',
	'247' => 'Abhoynagar',
	'248' => 'Bagherpara',
	'249' => 'Chowgacha',
	'250' => 'Jashore-S',
	'251' => 'Jhikargacha',
	'252' => 'Keshabpur',
	'253' => 'Monirampur',
	'254' => 'Sarsha',
	'255' => 'Harinakunda',
	'256' => 'Jhenaidah-S',
	'257' => 'Kaliganj',
	'258' => 'Kotchandpur',
	'259' => 'Moheshpur',
	'260' => 'Shailkupa',
	'261' => 'Batiaghata',
	'262' => 'Dacope',
	'263' => 'Dighalia',
	'264' => 'Dumuria',
	'265' => 'Koira',
	'266' => 'Paikgacha',
	'267' => 'Phultala',
	'268' => 'Rupsa',
	'269' => 'Terokhada',
	'270' => 'Bheramara',
	'271' => 'Daulatpur',
	'272' => 'Khoksha',
	'273' => 'Kumarkhali',
	'274' => 'Kushtia-S',
	'275' => 'Mirpur',
	'276' => 'Magura-S',
	'277' => 'Mohammadpur',
	'278' => 'Salikha',
	'279' => 'Sreepur',
	'280' => 'Gangni',
	'281' => 'Meherpur-S',
	'282' => 'Mujib Nagar',
	'283' => 'Kalia',
	'284' => 'Lohagara',
	'285' => 'Narail-S',
	'286' => 'Assasuni',
	'287' => 'Debhata',
	'288' => 'Kalaroa',
	'289' => 'Kaliganj',
	'290' => 'Satkhira-S',
	'291' => 'Shyamnagar',
	'292' => 'Tala',
	'293' => 'Bakshiganj',
	'294' => 'Dewanganj',
	'295' => 'Islampur',
	'296' => 'Jamalpur-S',
	'297' => 'Madarganj',
	'298' => 'Melendah',
	'299' => 'Sarishabari',
	'300' => 'Bhaluka',
	'301' => 'Dhobaura',
	'302' => 'Fulbaria',
	'303' => 'Gaffargaon',
	'304' => 'Gouripur',
	'305' => 'Haluaghat',
	'306' => 'Ishwarganj',
	'307' => 'Muktagacha',
	'308' => 'Mymensingh-S',
	'309' => 'Nandail',
	'310' => 'Phulpur',
	'311' => 'Tarakanda',
	'312' => 'Trishal',
	'313' => 'Atpara',
	'314' => 'Barhatta',
	'315' => 'Durgapur',
	'316' => 'Kalmakanda',
	'317' => 'Kendua',
	'318' => 'Khaliajuri',
	'319' => 'Madan',
	'320' => 'Mohanganj',
	'321' => 'Netrakona-S',
	'322' => 'Purbadhala',
	'323' => 'Jhenaigati',
	'324' => 'Nakla',
	'325' => 'Nalitabari',
	'326' => 'Sherpur-S',
	'327' => 'Sreebordi',
	'328' => 'Adamdighi',
	'329' => 'Bogura-S',
	'330' => 'Dhunot',
	'331' => 'Dhupchancia',
	'332' => 'Gabtali',
	'333' => 'Kahaloo',
	'334' => 'Nandigram',
	'335' => 'Sariakandi',
	'336' => 'Shajahanpur',
	'337' => 'Sherpur',
	'338' => 'Shibganj',
	'339' => 'Sonatala',
	'340' => 'Bholahat',
	'341' => 'Gomostapur',
	'342' => 'Nachol',
	'343' => 'Nawabganj-S',
	'344' => 'Shibganj',
	'345' => 'Akkelpur',
	'346' => 'Joypurhat-S',
	'347' => 'Kalai',
	'348' => 'Khetlal',
	'349' => 'Panchbibi',
	'350' => 'Atrai',
	'351' => 'Badalgachi',
	'352' => 'Dhamoirhat',
	'353' => 'Manda',
	'354' => 'Mohadevpur',
	'355' => 'Naogaon-S',
	'356' => 'Niamatpur',
	'357' => 'Patnitala',
	'358' => 'Porsha',
	'359' => 'Raninagar',
	'360' => 'Shapahar',
	'361' => 'Bagatipara',
	'362' => 'Baraigram',
	'363' => 'Gurudaspur',
	'364' => 'Lalpur',
	'365' => 'Naldanga',
	'366' => 'Natore-S',
	'367' => 'Singra',
	'368' => 'Atghoria',
	'369' => 'Bera',
	'370' => 'Bhangura',
	'371' => 'Chatmohar',
	'372' => 'Faridpur',
	'373' => 'Ishwardi',
	'374' => 'Pabna-S',
	'375' => 'Santhia',
	'376' => 'Sujanagar',
	'377' => 'Bagha',
	'378' => 'Bagmara',
	'379' => 'Charghat',
	'380' => 'Durgapur',
	'381' => 'Godagari',
	'382' => 'Mohanpur',
	'383' => 'Paba',
	'384' => 'Puthia',
	'385' => 'Tanore',
	'386' => 'Belkuchi',
	'387' => 'Chowhali',
	'388' => 'Kamarkhand',
	'389' => 'Kazipur',
	'390' => 'Raiganj',
	'391' => 'Shahzadpur',
	'392' => 'Sirajganj-S',
	'393' => 'Tarash',
	'394' => 'Ullapara',
	'395' => 'Birampur',
	'396' => 'Birganj',
	'397' => 'Birol',
	'398' => 'Bochaganj',
	'399' => 'Chirirbandar',
	'400' => 'Dinajpur-S',
	'401' => 'Fulbari',
	'402' => 'Ghoraghat',
	'403' => 'Hakimpur',
	'404' => 'Kaharol',
	'405' => 'Khanshama',
	'406' => 'Nawabganj',
	'407' => 'Parbatipur',
	'408' => 'Fulchari',
	'409' => 'Gaibandha-S',
	'410' => 'Gobindaganj',
	'411' => 'Palashbari',
	'412' => 'Sadullapur',
	'413' => 'Saghata',
	'414' => 'Sundarganj',
	'415' => 'Bhurungamari',
	'416' => 'Chilmari',
	'417' => 'Fulbari',
	'418' => 'Kurigram-S',
	'419' => 'Nageswari',
	'420' => 'Rajarhat',
	'421' => 'Rajibpur',
	'422' => 'Rowmari',
	'423' => 'Ulipur',
	'424' => 'Aditmari',
	'425' => 'Hatibandha',
	'426' => 'Kaliganj',
	'427' => 'Lalmonirhat-S',
	'428' => 'Patgram',
	'429' => 'Dimla',
	'430' => 'Domar',
	'431' => 'Jaldhaka',
	'432' => 'Kishoreganj Nilphamari',
	'433' => 'Nilphamari-S',
	'434' => 'Sayedpur',
	'435' => 'Atwari',
	'436' => 'Boda',
	'437' => 'Debiganj',
	'438' => 'Panchagarh-S',
	'439' => 'Tetulia',
	'440' => 'Badarganj',
	'441' => 'Gangachara',
	'442' => 'Kaunia',
	'443' => 'Mithapukur',
	'444' => 'Pirgacha',
	'445' => 'Pirganj',
	'446' => 'Rangpur-S',
	'447' => 'Taraganj',
	'448' => 'Baliadangi',
	'449' => 'Haripur',
	'450' => 'Pirganj',
	'451' => 'Ranisankail',
	'452' => 'Thakurgaon-S',
	'453' => 'Azmiriganj',
	'454' => 'Bahubal',
	'455' => 'Baniachong',
	'456' => 'Chunarughat',
	'457' => 'Habiganj-S',
	'458' => 'Lakhai',
	'459' => 'Madhabpur',
	'460' => 'Nabiganj',
	'461' => 'Sayestaganj',
	'462' => 'Barlekha',
	'463' => 'Juri',
	'464' => 'Kamalganj',
	'465' => 'Kulaura',
	'466' => 'Moulvibazar-S',
	'467' => 'Rajnagar',
	'468' => 'Sreemangal',
	'469' => 'Biswamvarpur',
	'470' => 'Chatak',
	'471' => 'Dakhin Sunamganj',
	'472' => 'Derai',
	'473' => 'Dharmapasha',
	'474' => 'Doarabazar',
	'475' => 'Jagannathpur',
	'476' => 'Jamalganj',
	'477' => 'Sulla',
	'478' => 'Sunamganj-S',
	'479' => 'Tahirpur',
	'480' => 'Balaganj',
	'481' => 'Beanibazar',
	'482' => 'Biswanath',
	'483' => 'Companiganj',
	'484' => 'Dakshin Surma',
	'485' => 'Fenchuganj',
	'486' => 'Golapganj',
	'487' => 'Gowainghat',
	'488' => 'Jointiapur',
	'489' => 'Kanaighat',
	'490' => 'Osmaninagar',
	'491' => 'Sylhet-S',
	'492' => 'Zakiganj'
];

// Cost purpose
$config['cost_purpose'] = array (
	'মোবাইল বিল',
	'ইন্টারনেট বিল',
	'স্টাফদের বেতন',
	'যাতায়াত খরচ',
	'ট্রন্সপোর্ট ভাড়া',
	'মোকামের হোটেল ভাড়া',
	'মোকামের খাবার',
	'মোকামের যাতায়াত ভাড়া',
	'মাল ক্রয় (ঢাকা)',
	'মাল ক্রয় (টাঙ্গাইল)',
	'মাল ক্রয় (পাবনা)',
	'দোকান ভাড়া',
	'বিদ্যুৎ বিল',
	'আপ্যায়ন খরচ',
	'রক্ষনাবেক্ষন',
	'গিফট প্রধান',
	'নাইট গার্ড',
	'মোকামের পার্টি আপ্যায়ন',
	'ষ্টেশনারী',
	'রিক্সা ভাড়া',
	'ভ্যান ভাড়া',
	'স্থানীয় মাল ক্রয়',
	'স্টাফের অগ্রীম বেতন',
	'তেল / মোবিল ক্রয়',
	'কর্য প্রদান',
	'ব্যাংক অনলাইন খরচ',
	'ইস্টিকার ক্রয়',
	'রোল ক্রয়',
	'ইলেক্টনিক্স মাল ক্রয়',
	'দান',
	'এম. ডি. স্যার',
	'বিবিদ'
);


//relation
$config['relation'] = array(
    "="   => "Equal",
   //"!="  => "Not Equal",
    ">"   => "Greater Than",
    //"<"   => "Less Than",
    ">="  => "Greater Than or Equal",
   // "<="  => "Less Than or Equal"
);



// privilege
$config['privilege'] = array('super', 'admin', 'user');

// branches
$config['branches'] = array("Branch 1", "Branch 2", "Branch 3","Branch 4","Branch 5");

//Developer Access
$config["developer"] = array(
    "username" => "freelanceitlab",
    "password" => "freelanceitlab" //#D~8WO7LLkX#
);

$config["days"] = array(
    "Saturday"  => "শনিবার",
    "Sunday"    => "রবিবার",
    "Monday"    => "সোমবার",
    "Tuesday"   => "মঙ্গলবার",
    "Wednesday" => "বুধবার",
    "Thursday"  => "বৃহস্পতিবার",
    "Friday"    => "শুক্রবার"
);
$config['banks']=array("Sonali_Bank_Limited", "Agrani_Bank_Limited", "Rupali_Bank_Limited", "AB_Bank_Limited", "Jamuna_Bank_Limited","Janata_Bank_Limited", "National_Bank_Limited", "NCC_Bank_Limited", "Prime_Bank_Limited", "Standard_Bank_Limited", "The_City_Bank_Limited", "Trust_Bank_Limited", "Islami_Bank_Bangladesh_Limited", "The_City_Bank_Limited", "Dutch_Bangla_Bank");
//Income_Purpose
$config["income_purpose"] = array(
    'পরিবহন' => 'পরিবহন',
    'ষ্টেশনারী বিক্রয়' => 'ষ্টেশনারী বিক্রয়',
    'কার্ড জমা' => 'কার্ড জমা',
    'বই বিক্রি' => 'বই বিক্রি',
    'খাতা বিক্রি' => 'খাতা বিক্রি',
    'পুরাতন কাগজ বিক্রি' => 'পুরাতন কাগজ বিক্রি',
    'পুরাতন আসবাবপত্র বিক্রি' => 'পুরাতন আসবাবপত্র বিক্রি'
);
